### ISSUE TITLE
Build task examples is failing

### ISSUE THREAD

**Issue by ray-delossantos** [openpeeps/tim#14]
When running nimble task **examples** it's returning an error:

```console
Error: attempting to call undeclared routine: 'addPlaceholder'
```

**Comment by georgelemon** [comment]
Yes, things are pretty messy right now. Will take a look

**Comment by georgelemon** [comment]
Installing Tim from nimble `nimble install tim#@head` will build the cli app. This will include a S2S transpiler (not done), for now only HTML output is usable, Using the CLi should be faster for playing around, for example `tim src -t:html some.timl`

**Comment by ray-delossantos** [comment]
Thanks for the quick fix. I was able to test properly.
